# Generated by Django 5.0.2 on 2024-03-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_ticket_price_ticket_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='0C81300808', max_length=50, unique=True),
        ),
    ]
