# Generated by Django 5.0.2 on 2024-03-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='E18B43B6EC', max_length=50, unique=True),
        ),
    ]
