# Generated by Django 5.0.2 on 2024-03-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='DFE4A70CA2', max_length=50, unique=True),
        ),
    ]
