# Generated by Django 5.0.2 on 2024-03-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='8182E56D65', max_length=50, unique=True),
        ),
    ]
