# Generated by Django 5.0.2 on 2024-03-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='E0BB9D68BD', max_length=50, unique=True),
        ),
    ]
