# Generated by Django 5.0.2 on 2024-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='C4BAF8CE22', max_length=50, unique=True),
        ),
    ]
