# Generated by Django 5.0.2 on 2024-03-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='C74E36CF37', max_length=50, unique=True),
        ),
    ]
