# Generated by Django 5.0.2 on 2024-03-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_alter_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='955F9A0ACF', max_length=50, unique=True),
        ),
    ]
