# Generated by Django 5.0.2 on 2024-03-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_alter_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='4CFB1F961A', max_length=50, unique=True),
        ),
    ]
