# Generated by Django 5.0.2 on 2024-03-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_alter_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='C3AD7FE8B5', max_length=50, unique=True),
        ),
    ]
