# Generated by Django 5.0.2 on 2024-03-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='A2ECE877A0', max_length=50, unique=True),
        ),
    ]
