# Generated by Django 5.0.2 on 2024-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_alter_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='9E9DFBB923', max_length=50, unique=True),
        ),
    ]
