# Generated by Django 5.0.2 on 2024-03-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTaskManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('messaging.message',),
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='sent_on',
        ),
    ]
