# Generated by Django 5.0.2 on 2024-03-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messagetaskmanager_rename_timestamp_message_sent_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageTaskManager',
        ),
    ]
