EVENT_STATUS = [
    ('Disabled', 'Disabled'),
    ('Active', 'Active'),
    ('Private', 'Private'),
    ('Deleted', 'Deleted'),
    ('Time out', 'Time Out'),
    ('Completed', 'Completed'),
    ('Cancel', 'Cancel'),
]

EVENT_TYPES = [
    ('Concerts & Festivals', 'Concerts & Festivals'),
    ('Sports', 'Sports'),
    ('Cultural', 'Cultural'),
    ('Education', 'Education'),
    ('Community', 'Community'),
    ('Entertainment', 'Entertainment'),
    ('Science & Technology', 'Science & Technology'),
    ('Finance & Business', 'Finance & Business'),
    ('Fashion', 'Fashion'),
    ('Arts & Crafts', 'Arts & Crafts'),
    ('Religious & Spiritual', 'Religious & Spiritual'),
    ('Food & Beverage', 'Food & Beverage'),
    ('Hobbies & Interests', 'Hobbies & Interests'),
    ('Environment', 'Environment'),
    ('Automotive', 'Automotive'),
    ('Manufacturing', 'Manufacturing'),
    ('Retail', 'Retail'),
    ('Health and Wellness', 'Health and Wellness'),
    ('Hospitality and Tourism', 'Hospitality and Tourism'),
    ('Energy', 'Energy'),
    ('Fundraising & Charity', 'Fundraising & Charity'),
    ('Telecommunications', 'Telecommunications'),
    ('Construction and Real Estate', 'Construction and Real Estate'),
    ('Transportation and Logistics', 'Transportation and Logistics'),
    ('Government and Non-Profit', 'Government and Non-Profit'),
    ('Consulting and Professional Services', 'Consulting and Professional Services'),
    ('Other', 'Other')
]

REGIONS = [
    ('Blagoevgrad', 'Blagoevgrad'),
    ('Burgas', 'Burgas'),
    ('Dobrich', 'Dobrich'),
    ('Gabrovo', 'Gabrovo'),
    ('Haskovo', 'Haskovo'),
    ('Kardzhali', 'Kardzhali'),
    ('Kyustendil', 'Kyustendil'),
    ('Lovech', 'Lovech'),
    ('Montana', 'Montana'),
    ('Pazardzhik', 'Pazardzhik'),
    ('Pernik', 'Pernik'),
    ('Pleven', 'Pleven'),
    ('Plovdiv', 'Plovdiv'),
    ('Razgrad', 'Razgrad'),
    ('Ruse', 'Ruse'),
    ('Shumen', 'Shumen'),
    ('Silistra', 'Silistra'),
    ('Sliven', 'Sliven'),
    ('Smolyan', 'Smolyan'),
    ('Sofia', 'Sofia'),
    ('Stara Zagora', 'Stara Zagora'),
    ('Targovishte', 'Targovishte'),
    ('Varna', 'Varna'),
    ('Veliko Tarnovo', 'Veliko Tarnovo'),
    ('Vidin', 'Vidin'),
    ('Vratsa', 'Vratsa'),
    ('Yambol', 'Yambol')
]
