# Generated by Django 5.0.2 on 2024-03-29 11:00

import django.db.models.deletion
import eventygram.events.helpers
import eventygram.events.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('region', models.CharField(blank=True, choices=[('Blagoevgrad', 'Blagoevgrad'), ('Burgas', 'Burgas'), ('Dobrich', 'Dobrich'), ('Gabrovo', 'Gabrovo'), ('Haskovo', 'Haskovo'), ('Kardzhali', 'Kardzhali'), ('Kyustendil', 'Kyustendil'), ('Lovech', 'Lovech'), ('Montana', 'Montana'), ('Pazardzhik', 'Pazardzhik'), ('Pernik', 'Pernik'), ('Pleven', 'Pleven'), ('Plovdiv', 'Plovdiv'), ('Razgrad', 'Razgrad'), ('Ruse', 'Ruse'), ('Shumen', 'Shumen'), ('Silistra', 'Silistra'), ('Sliven', 'Sliven'), ('Smolyan', 'Smolyan'), ('Sofia', 'Sofia'), ('Stara Zagora', 'Stara Zagora'), ('Targovishte', 'Targovishte'), ('Varna', 'Varna'), ('Veliko Tarnovo', 'Veliko Tarnovo'), ('Vidin', 'Vidin'), ('Vratsa', 'Vratsa'), ('Yambol', 'Yambol')], max_length=100, null=True)),
                ('location', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=eventygram.events.helpers.event_pic_path)),
                ('start_time', models.DateTimeField(validators=[eventygram.events.validators.validate_start_time])),
                ('end_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('Concerts & Festivals', 'Concerts & Festivals'), ('Sports', 'Sports'), ('Cultural', 'Cultural'), ('Education', 'Education'), ('Community', 'Community'), ('Entertainment', 'Entertainment'), ('Science & Technology', 'Science & Technology'), ('Finance & Business', 'Finance & Business'), ('Fashion', 'Fashion'), ('Arts & Crafts', 'Arts & Crafts'), ('Religious & Spiritual', 'Religious & Spiritual'), ('Food & Beverage', 'Food & Beverage'), ('Hobbies & Interests', 'Hobbies & Interests'), ('Environment', 'Environment'), ('Automotive', 'Automotive'), ('Manufacturing', 'Manufacturing'), ('Retail', 'Retail'), ('Health and Wellness', 'Health and Wellness'), ('Hospitality and Tourism', 'Hospitality and Tourism'), ('Energy', 'Energy'), ('Fundraising & Charity', 'Fundraising & Charity'), ('Telecommunications', 'Telecommunications'), ('Construction and Real Estate', 'Construction and Real Estate'), ('Transportation and Logistics', 'Transportation and Logistics'), ('Government and Non-Profit', 'Government and Non-Profit'), ('Consulting and Professional Services', 'Consulting and Professional Services'), ('Other', 'Other')], max_length=100)),
                ('status', models.CharField(blank=True, choices=[('Disabled', 'Disabled'), ('Active', 'Active'), ('Private', 'Private'), ('Deleted', 'Deleted'), ('Time out', 'Time Out'), ('Completed', 'Completed'), ('Cancel', 'Cancel')], default='Active', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('likes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_creator', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
