# Generated by Django 5.0.2 on 2024-03-16 21:40

import django.core.validators
import django.db.models.deletion
import eventygram.events.helpers
import eventygram.events.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=eventygram.events.helpers.event_pic_path)),
                ('start_time', models.DateTimeField(validators=[eventygram.events.validators.validate_start_time])),
                ('end_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('Concerts', 'Concerts'), ('Sports', 'Sports'), ('Cultural', 'Cultural'), ('Educational', 'Educational'), ('Community', 'Community'), ('Political', 'Political'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment'), ('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Manufacturing', 'Manufacturing'), ('Retail', 'Retail'), ('Hospitality and Tourism', 'Hospitality and Tourism'), ('Energy', 'Energy'), ('Telecommunications', 'Telecommunications'), ('Construction and Real Estate', 'Construction and Real Estate'), ('Media and Entertainment', 'Media and Entertainment'), ('Transportation and Logistics', 'Transportation and Logistics'), ('Government and Non-Profit', 'Government and Non-Profit'), ('Consulting and Professional Services', 'Consulting and Professional Services'), ('Other', 'Other')], max_length=100)),
                ('tickets_sales', models.BooleanField(default=False)),
                ('available_tickets', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('Disabled', 'Disabled'), ('Active', 'Active'), ('Deleted', 'Deleted'), ('Time out', 'Time Out'), ('Completed', 'Completed'), ('Cancel', 'Cancel')], null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_creator', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
