# Generated by Django 5.0.2 on 2024-03-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
