# Generated by Django 5.0.2 on 2024-03-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_private_event_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTaskManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
    ]
