# Generated by Django 5.0.2 on 2024-03-10 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_start_date_event_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='type',
        ),
    ]
