# Generated by Django 5.0.2 on 2024-03-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventtaskmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('Disabled', 'Disabled'), ('Active', 'Active'), ('Deleted', 'Deleted'), ('Time out', 'Time Out'), ('Completed', 'Completed'), ('Cancel', 'Cancel')], default='Active', null=True),
        ),
    ]
