# Generated by Django 5.0.2 on 2024-03-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
