# Generated by Django 5.0.2 on 2024-03-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_private',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('Disabled', 'Disabled'), ('Active', 'Active'), ('Private', 'Private'), ('Deleted', 'Deleted'), ('Time out', 'Time Out'), ('Completed', 'Completed'), ('Cancel', 'Cancel')], default='Active', null=True),
        ),
    ]
