# Generated by Django 5.0.2 on 2024-03-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
