# Generated by Django 5.0.2 on 2024-03-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_organization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_user',
        ),
    ]
