# Generated by Django 5.0.2 on 2024-03-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, choices=[('Blagoevgrad', 'Blagoevgrad'), ('Burgas', 'Burgas'), ('Dobrich', 'Dobrich'), ('Gabrovo', 'Gabrovo'), ('Haskovo', 'Haskovo'), ('Kardzhali', 'Kardzhali'), ('Kyustendil', 'Kyustendil'), ('Lovech', 'Lovech'), ('Montana', 'Montana'), ('Pazardzhik', 'Pazardzhik'), ('Pernik', 'Pernik'), ('Pleven', 'Pleven'), ('Plovdiv', 'Plovdiv'), ('Razgrad', 'Razgrad'), ('Ruse', 'Ruse'), ('Shumen', 'Shumen'), ('Silistra', 'Silistra'), ('Sliven', 'Sliven'), ('Smolyan', 'Smolyan'), ('Sofia', 'Sofia'), ('Stara Zagora', 'Stara Zagora'), ('Targovishte', 'Targovishte'), ('Varna', 'Varna'), ('Veliko Tarnovo', 'Veliko Tarnovo'), ('Vidin', 'Vidin'), ('Vratsa', 'Vratsa'), ('Yambol', 'Yambol')], max_length=100, null=True),
        ),
    ]
