# Generated by Django 5.0.2 on 2024-03-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('User', 'User'), ('Company', 'Company'), ('Organization', 'Organization')], max_length=20),
        ),
    ]
