# Generated by Django 5.0.2 on 2024-03-06 20:31

import eventygram.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_age_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=eventygram.accounts.models.profile_pic_path),
        ),
    ]
