# Generated by Django 5.0.2 on 2024-03-18 09:06

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profilesubscriber_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTaskManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
