# Generated by Django 5.0.2 on 2024-03-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profiletaskmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
