# Generated by Django 5.0.2 on 2024-03-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileTaskManager',
        ),
    ]
