# Generated by Django 5.0.2 on 2024-03-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_profiletaskmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_theme',
            field=models.CharField(blank=True, choices=[('background1.jpg', 'Theme 1'), ('background2.jpg', 'Theme 2'), ('background3.jpg', 'Theme 3'), ('background4.jpg', 'Theme 4'), ('background5.jpg', 'Theme 5'), ('background6.jpg', 'Theme 6'), ('background7.jpg', 'Theme 7')], default='background1.jpg', max_length=100, null=True),
        ),
    ]
