# Generated by Django 5.0.2 on 2024-03-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_profile_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_theme',
        ),
    ]
