# Generated by Django 5.0.2 on 2024-03-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacthistory',
            options={'verbose_name_plural': 'Contact history'},
        ),
    ]
